"""add_interactions_table

Revision ID: 702832c52976
Revises: 20240224_000001
Create Date: 2026-02-25 09:29:58.159580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '702832c52976'
down_revision = '20240224_000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.String(length=255), server_default=sa.text("gen_random_uuid()::text"), nullable=False),
    sa.Column('fund_id', sa.String(length=255), nullable=False),
    sa.Column('contact_id', sa.String(length=255), nullable=True),
    sa.Column('interaction_type', sa.Enum('EMAIL', 'MEETING', 'NOTE', 'CALL', 'INTRO', 'SOCIAL', name='interaction_type_enum'), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='interaction_direction_enum'), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('source_table', sa.String(length=50), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interactions')
    # ### end Alembic commands ###
