"""Rename metadata to custom_metadata in bdr_companies

Revision ID: b3b9e7a0f5f8
Revises: 20250303_000001
Create Date: 2026-03-03 07:39:18.535554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3b9e7a0f5f8'
down_revision = '20250303_000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bdr_notes')
    op.drop_index(op.f('idx_bdr_meetings_scheduled_at'), table_name='bdr_meetings')
    op.drop_table('bdr_meetings')
    op.drop_index(op.f('idx_email_templates_category'), table_name='email_templates')
    op.drop_index(op.f('idx_email_templates_is_active'), table_name='email_templates')
    op.drop_index(op.f('idx_email_templates_is_default'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('idx_bdr_companies_priority'), table_name='bdr_companies')
    op.drop_index(op.f('idx_bdr_companies_status'), table_name='bdr_companies')
    op.drop_table('bdr_companies')
    op.drop_index(op.f('idx_bdr_contacts_company_id'), table_name='bdr_contacts')
    op.drop_index(op.f('idx_bdr_contacts_email'), table_name='bdr_contacts')
    op.drop_table('bdr_contacts')
    op.drop_index(op.f('idx_bdr_outreach_attempts_contact_id'), table_name='bdr_outreach_attempts')
    op.drop_index(op.f('idx_bdr_outreach_attempts_status'), table_name='bdr_outreach_attempts')
    op.drop_table('bdr_outreach_attempts')
    op.drop_table('bdr_sequences')
    op.drop_table('bdr_campaigns')
    op.drop_table('bdr_batches')
    op.alter_column('funds', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funds', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('bdr_batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('batch_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('target_count', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('completed_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bdr_batches_pkey'))
    )
    op.create_table('bdr_campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('campaign_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('campaign_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('target_accounts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_persona', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=True),
    sa.Column('total_contacts_added', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_emails_sent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_replies', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_meetings_booked', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("campaign_type::text = ANY (ARRAY['OUTBOUND'::character varying, 'INBOUND'::character varying, 'RETARGETING'::character varying, 'REFERRAL'::character varying, 'EVENT'::character varying]::text[])", name=op.f('bdr_campaigns_campaign_type_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['DRAFT'::character varying, 'ACTIVE'::character varying, 'PAUSED'::character varying, 'COMPLETED'::character varying, 'ARCHIVED'::character varying]::text[])", name=op.f('bdr_campaigns_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('bdr_campaigns_pkey'))
    )
    op.create_table('bdr_sequences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('sequence_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_icp', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_steps', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('days_between_steps', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bdr_sequences_pkey'))
    )
    op.create_table('bdr_outreach_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('outreach_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subject_line', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('body_preview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('clicked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('replied_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reply_sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('reply_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meeting_booked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("direction::text = ANY (ARRAY['OUTBOUND'::character varying, 'INBOUND'::character varying, 'REPLY'::character varying]::text[])", name=op.f('bdr_outreach_attempts_direction_check')),
    sa.CheckConstraint("outreach_type::text = ANY (ARRAY['EMAIL'::character varying, 'LINKEDIN'::character varying, 'COLD_CALL'::character varying, 'VOICEMAIL'::character varying, 'SOCIAL'::character varying, 'VIDEO'::character varying, 'DIRECT_MAIL'::character varying, 'OTHER'::character varying]::text[])", name=op.f('bdr_outreach_attempts_outreach_type_check')),
    sa.CheckConstraint("reply_sentiment::text = ANY (ARRAY['POSITIVE'::character varying, 'NEUTRAL'::character varying, 'NEGATIVE'::character varying]::text[])", name=op.f('bdr_outreach_attempts_reply_sentiment_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['SCHEDULED'::character varying, 'SENT'::character varying, 'DELIVERED'::character varying, 'OPENED'::character varying, 'CLICKED'::character varying, 'REPLIED'::character varying, 'BOUNCED'::character varying, 'UNSUBSCRIBED'::character varying, 'MEETING_BOOKED'::character varying, 'NOT_INTERESTED'::character varying]::text[])", name=op.f('bdr_outreach_attempts_status_check')),
    sa.ForeignKeyConstraint(['company_id'], ['bdr_companies.id'], name=op.f('bdr_outreach_attempts_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['bdr_contacts.id'], name=op.f('bdr_outreach_attempts_contact_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bdr_outreach_attempts_pkey'))
    )
    op.create_index(op.f('idx_bdr_outreach_attempts_status'), 'bdr_outreach_attempts', ['status'], unique=False)
    op.create_index(op.f('idx_bdr_outreach_attempts_contact_id'), 'bdr_outreach_attempts', ['contact_id'], unique=False)
    op.create_table('bdr_contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seniority_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_decision_maker', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_champion', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_contacted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('contact_preference', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['bdr_companies.id'], name=op.f('bdr_contacts_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bdr_contacts_pkey'))
    )
    op.create_index(op.f('idx_bdr_contacts_email'), 'bdr_contacts', ['email'], unique=False)
    op.create_index(op.f('idx_bdr_contacts_company_id'), 'bdr_contacts', ['company_id'], unique=False)
    op.create_table('bdr_companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('company_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('annual_revenue', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('headquarters_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('headquarters_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('headquarters_country', sa.VARCHAR(length=100), server_default=sa.text("'USA'::character varying"), autoincrement=False, nullable=True),
    sa.Column('website_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ideal_buyer_persona', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pain_points', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('use_case_fit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=10), server_default=sa.text("'B'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'NEW'::character varying"), autoincrement=False, nullable=True),
    sa.Column('lead_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('icp_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('assigned_bdr', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_activity_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.CheckConstraint("priority::text = ANY (ARRAY['A'::character varying, 'B'::character varying, 'C'::character varying]::text[])", name=op.f('bdr_companies_priority_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['NEW'::character varying, 'RESEARCHING'::character varying, 'CONTACTED'::character varying, 'ENGAGED'::character varying, 'OPPORTUNITY'::character varying, 'CLOSED_WON'::character varying, 'CLOSED_LOST'::character varying, 'NURTURE'::character varying]::text[])", name=op.f('bdr_companies_status_check')),
    sa.CheckConstraint('icp_score >= 0 AND icp_score <= 100', name=op.f('bdr_companies_icp_score_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('bdr_companies_pkey'))
    )
    op.create_index(op.f('idx_bdr_companies_status'), 'bdr_companies', ['status'], unique=False)
    op.create_index(op.f('idx_bdr_companies_priority'), 'bdr_companies', ['priority'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('variables', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_templates_pkey')),
    sa.UniqueConstraint('name', name=op.f('email_templates_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_email_templates_is_default'), 'email_templates', ['is_default'], unique=False)
    op.create_index(op.f('idx_email_templates_is_active'), 'email_templates', ['is_active'], unique=False)
    op.create_index(op.f('idx_email_templates_category'), 'email_templates', ['category'], unique=False)
    op.create_table('bdr_meetings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meeting_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('meeting_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'SCHEDULED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_steps', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("meeting_type::text = ANY (ARRAY['DISCOVERY'::character varying, 'DEMO'::character varying, 'FOLLOW_UP'::character varying, 'CLOSING'::character varying, 'INTRO'::character varying]::text[])", name=op.f('bdr_meetings_meeting_type_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['SCHEDULED'::character varying, 'COMPLETED'::character varying, 'NO_SHOW'::character varying, 'CANCELLED'::character varying, 'RESCHEDULED'::character varying]::text[])", name=op.f('bdr_meetings_status_check')),
    sa.ForeignKeyConstraint(['company_id'], ['bdr_companies.id'], name=op.f('bdr_meetings_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['bdr_contacts.id'], name=op.f('bdr_meetings_contact_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bdr_meetings_pkey'))
    )
    op.create_index(op.f('idx_bdr_meetings_scheduled_at'), 'bdr_meetings', ['scheduled_at'], unique=False)
    op.create_table('bdr_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('contact_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('note_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pinned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("note_type::text = ANY (ARRAY['CALL'::character varying, 'EMAIL'::character varying, 'LINKEDIN'::character varying, 'RESEARCH'::character varying, 'MEETING'::character varying, 'OTHER'::character varying]::text[])", name=op.f('bdr_notes_note_type_check')),
    sa.ForeignKeyConstraint(['company_id'], ['bdr_companies.id'], name=op.f('bdr_notes_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['bdr_contacts.id'], name=op.f('bdr_notes_contact_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bdr_notes_pkey'))
    )
    # ### end Alembic commands ###
